### ISSUE TITLE
INTERVAL_SIZE discrepency? 

### ISSUE THREAD

**Issue by EdenSegal** [pranith/qpoints#1]
Hi, 
The bbv plugin uses INTERVAL_SIZE of 100M, while tracer uses INTERVAL_SIZE of 10M. I think it's a typo, because near the 10M a comment says 100M, but the number is wrong. I think it's quite bad that the two aren't the same. 
Thanks,
Eden Segal

**Comment by pranith** [comment]
Fixed in 4474bc7de5b770bce8c6561e2b0f67bda54a1ecf. Thanks for reporting!
